function generateProjects(lang) {

  // 👉 PYTHON
  if (lang === "Python") {
    return [
      { name: "Python Project 1", code: `print("Hello Python")` },
      { name: "Python Project 2", code: `numbers = [random.randint(1, 100) for _ in range(10)]\neven_numbers = [n for n in numbers if n % 2 == 0]\nprint("Random Numbers:", numbers)\nprint("Even Numbers:", even_numbers)\ntotal = sum(numbers)\naverage = total / len(numbers)\nprint("Sum:", total)
print("Average:", average)` },
      { name: "Python Project 3", code: `import random\nnums=[random.randint(1,50) for _ in range(20)]\nsquared=[x**2 for x in nums]\nfiltered=[x for x in squared if x%3==0]\ndef calc_sum(lst):\n    return sum(lst)\ndef calc_avg(lst):\n    return sum(lst)/len(lst) if lst else 0\nresult_sum=calc_sum(filtered)\nresult_avg=calc_avg(filtered)\nprint("Nums:",nums)\nprint("Squared:",squared)\nprint("Filtered:",filtered)\nprint("Sum:",result_sum)\nprint("Avg:",result_avg)` },
      { name: "Python Project 4", code: `data="hello world python coding"\nwords=data.split()\nrev_words=[w[::-1] for w in words]\nupper=[w.upper() for w in rev_words]\ndef join_words(lst):\n    return "-".join(lst)\ndef count_chars(lst):\n    return sum(len(w) for w in lst)\njoined=join_words(upper)\nchar_count=count_chars(upper)\nprint("Words:",words)\nprint("Reversed:",rev_words)\nprint("Upper:",upper)\nprint("Joined:",joined)\nprint("Count:",char_count)` },
      { name: "Python Project 5", code: `import math\nnums=[i for i in range(1,21)]\nsqrt_vals=[math.sqrt(x) for x in nums]\nfloored=[math.floor(x) for x in sqrt_vals]\ndef is_even(n):\n    return n%2==0\nevens=list(filter(is_even,floored))\ntotal=sum(evens)\nmax_val=max(evens) if evens else 0\nprint("Nums:",nums)\nprint("Sqrt:",sqrt_vals)\nprint("Floored:",floored)\nprint("Evens:",evens)\nprint("Total:",total)\nprint("Max:",max_val)` },
      { name: "Python Project 6", code: `students={"a":85,"b":92,"c":78,"d":88}\ngrades={}\nfor k,v in students.items():\n    if v>90:\n        grades[k]="A"\n    elif v>80:\n        grades[k]="B"\n    else:\n        grades[k]="C"\ndef avg_marks(d):\n    return sum(d.values())/len(d)\navg=avg_marks(students)\nprint("Students:",students)\nprint("Grades:",grades)\nprint("Average:",avg)` },
      { name: "Python Project 7", code: `random\nmatrix=[[random.randint(1,9) for _ in range(3)] for _ in range(3)]\ntransposed=list(zip(*matrix))\ndef flatten(m):\n    return [item for row in m for item in row]\nflat=flatten(matrix)\nunique=set(flat)\nsorted_vals=sorted(unique)\nsum_vals=sum(flat)\nprint("Matrix:",matrix)\nprint("Transpose:",transposed)\nprint("Flat:",flat)\nprint("Unique:",unique)\nprint("Sorted:",sorted_vals)\nprint("Sum:",sum_vals)` },
      { name: "Python Project 8", code: `text="python is fun and powerful"\nvowels="aeiou"\nvowel_count={v:0 for v in vowels}\nfor ch in text:\n    if ch in vowels:\n        vowel_count[ch]+=1\ndef most_used(d):\n    return max(d,key=d.get)\nmost=most_used(vowel_count)\ntotal=sum(vowel_count.values())\nprint("Text:",text)\nprint("Vowels:",vowel_count)\nprint("Most:",most)\nprint("Total:",total)` },
      { name: "Python Project 9", code: `nums=list(range(1,15))\nodd=[x for x in nums if x%2!=0]\neven=[x for x in nums if x%2==0]\ndef multiply(lst):\n    res=1\n    for x in lst:\n        res*=x\n    return res\nodd_mul=multiply(odd)\neven_mul=multiply(even)\nprint("Nums:",nums)\nprint("Odd:",odd)\nprint("Even:",even)\nprint("OddMul:",odd_mul)\nprint("EvenMul:",even_mul)` },
      { name: "Python Project 10", code: `import random\nchoices=["rock","paper","scissors"]\nuser=random.choice(choices)\ncomp=random.choice(choices)\ndef decide(u,c):\n    if u==c:\n        return "Draw"\n    elif (u=="rock" and c=="scissors") or (u=="paper" and c=="rock") or (u=="scissors" and c=="paper"):\n        return "Win"\n    else:\n        return "Lose"\nresult=decide(user,comp)\nprint("User:",user)\nprint("Comp:",comp)\nprint("Result:",result)` }
    ];
  }

  // 👉 JAVA
  if (lang === "Java") {
    return [
      { name: "Java Project 1", code: `import java.util.*;\nclass Main{\npublic static void main(String[] args){\nList<Integer> list=new ArrayList<>();\nRandom r=new Random();\nfor(int i=0;i<15;i++){\nlist.add(r.nextInt(100));\n}\nList<Integer> even=new ArrayList<>();\nfor(int n:list){\nif(n%2==0){\neven.add(n);\n}\n}\nSystem.out.println(list);\nSystem.out.println(even);\n}}` },
      { name: "Java Project 2", code: `import java.util.*;\nclass Demo{\npublic static void main(String[] args){\nString s="java typing practice";\nString[] arr=s.split(" ");\nList<String> rev=new ArrayList<>();\nfor(String w:arr){\nrev.add(new StringBuilder(w).reverse().toString());\n}\nCollections.sort(rev);\nint count=0;\nfor(String w:rev){\ncount+=w.length();\n}\nSystem.out.println(rev);\nSystem.out.println(count);\n}` },
      { name: "Java Project 3", code: `import java.util.*;\nclass Test{\npublic static void main(String[] args){\nMap<String,Integer> map=new HashMap<>();\nmap.put("A",10);\nmap.put("B",20);\nmap.put("C",30);\nint sum=0;\nfor(int v:map.values()){\nsum+=v;\n}\ndouble avg=sum/map.size();\nSystem.out.println(map);\nSystem.out.println(sum);\nSystem.out.println(avg);\n}}` },
      { name: "Java Project 4", code: `import java.util.*;\nclass Main{\npublic static void main(String[] args){\nList<String> names=Arrays.asList("ram","shyam","mohan");\nList<String> upper=new ArrayList<>();\nfor(String n:names){\nupper.add(n.toUpperCase());\n}\nCollections.reverse(upper);\nint len=0;\nfor(String s:upper){\nlen+=s.length();\n}\nSystem.out.println(upper);\nSystem.out.println(len);\n}}` },
      { name: "Java Project 5", code: `import java.util.*;\nclass App{\npublic static void main(String[] args){\nint[] arr=new int[10];\nRandom r=new Random();\nfor(int i=0;i<arr.length;i++){\narr[i]=r.nextInt(50);\n}\nint max=arr[0];\nfor(int n:arr){\nif(n>max)max=n;\n}\nArrays.sort(arr);\nSystem.out.println(Arrays.toString(arr));\nSystem.out.println(max);\n}}` },
      { name: "Java Project 6", code: `import java.util.*;\nclass Code{\npublic static void main(String[] args){\nString str="learning java is fun";\nchar[] ch=str.toCharArray();\nMap<Character,Integer> freq=new HashMap<>();\nfor(char c:ch){\nfreq.put(c,freq.getOrDefault(c,0)+1);\n}\nfor(char c:freq.keySet()){\nSystem.out.println(c+":"+freq.get(c));\n}\n}}` },
      { name: "Java Project 7", code: `import java.util.*;\nclass Run{\npublic static void main(String[] args){\nList<Integer> nums=Arrays.asList(1,2,3,4,5);\nList<Integer> sq=new ArrayList<>();\nfor(int n:nums){\nsq.add(n*n);\n}\nint sum=0;\nfor(int n:sq){\nsum+=n;\n}\nSystem.out.println(nums);\nSystem.out.println(sq);\nSystem.out.println(sum);\n}}` },
      { name: "Java Project 8", code: `import java.util.*;\nclass Demo{\npublic static void main(String[] args){\nScanner sc=new Scanner(System.in);\nint n=5;\nList<Integer> list=new ArrayList<>();\nfor(int i=0;i<n;i++){\nlist.add(i*2);\n}\nCollections.shuffle(list);\nint min=Collections.min(list);\nSystem.out.println(list);\nSystem.out.println(min);\n}}` },
      { name: "Java Project 9", code: `import java.util.*;\nclass Main{\npublic static void main(String[] args){\nString s="abcdef";\nList<String> list=new ArrayList<>();\nfor(int i=0;i<s.length();i++){\nlist.add(s.substring(0,i+1));\n}\nCollections.reverse(list);\nfor(String x:list){\nSystem.out.println(x);\n}\n}` },
      { name: "Java Project 10", code: `import java.util.*;\nclass App{\npublic static void main(String[] args){\nint n=10;\nList<Integer> fib=new ArrayList<>();\nfib.add(0);\nfib.add(1);\nfor(int i=2;i<n;i++){\nfib.add(fib.get(i-1)+fib.get(i-2));\n}\nint sum=0;\nfor(int x:fib){\nsum+=x;\n}\nSystem.out.println(fib);\nSystem.out.println(sum);\n}}` }
    ];
  }

  // 👉 C++
  if (lang === "C++") {
    return [
      { name: "C++ Project 1", code: `[3:58 pm, 15/05/2026] Garad: 1
[3:58 pm, 15/05/2026] Garad: #include <iostream>\n#include <vector>\nusing namespace std;\nint main(){\n vector<int> v;\n for(int i=1;i<=10;i++){\n  v.push_back(i);\n }\n for(int i=0;i<v.size();i++){\n  v[i]=v[i]*2;\n }\n int sum=0;\n for(int x:v){\n  sum+=x;\n }\n cout<<"Sum:"<<sum<<endl;\n for(int x:v){\n  cout<<x<<" ";\n }\n cout<<endl;\n return 0;\n}` },
      { name: "C++ Project 2", code: `#include <vector>\n#include <iostream>\nusing namespace std;\nint main(){\n vector<int> v={1,2,3,4,5};\n for(int i=0;i<v.size();i++){\n  v[i]=v[i]*v[i];\n }\n for(auto x:v){\n  cout<<x<<" ";\n }\n cout<<endl;\n int sum=0;\n for(int x:v){\n  sum+=x;\n }\n cout<<sum;\n return 0;\n}` },
      { name: "C++ Project 3", code: `#include <map>\n#include <iostream>\nusing namespace std;\nint main(){\n map<string,int> m;\n m["a"]=1;\n m["b"]=2;\n m["c"]=3;\n for(auto it:m){\n  cout<<it.first<<"="<<it.second<<endl;\n }\n int total=0;\n for(auto it:m){\n  total+=it.second;\n }\n cout<<total;\n return 0;\n}` },
      { name: "C++ Project 4", code: `#include <algorithm>\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){\n vector<int> v={9,3,5,1,7};\n sort(v.begin(),v.end());\n reverse(v.begin(),v.end());\n for(int i=0;i<v.size();i++){\n  cout<<v[i]<<" ";\n }\n cout<<endl;\n int mx=*max_element(v.begin(),v.end());\n cout<<mx;\n return 0;\n}` },
      { name: "C++ Project 5", code: `#include <string>\n#include <iostream>\nusing namespace std;\nint main(){\n string s="hello";\n string r="";\n for(int i=s.size()-1;i>=0;i--){\n  r+=s[i];\n }\n cout<<r<<endl;\n if(s==r){\n  cout<<"palindrome";\n }else{\n  cout<<"not";\n }\n return 0;\n}` },
      { name: "C++ Project 6", code: `#include <iostream>\n#include <map>\nusing namespace std;\nint main(){\n map<string,int> m;\n m["ram"]=50;\n m["shyam"]=70;\n m["om"]=90;\n for(auto x:m){\n  cout<<x.first<<" "<<x.second<<endl;\n }\n int maxMarks=0;\n string topper;\n for(auto x:m){\n  if(x.second>maxMarks){\n   maxMarks=x.second;\n   topper=x.first;\n  }\n }\n cout<<"Topper:"<<topper;\n return 0;\n}` },
      { name: "C++ Project 7", code: `#include <iostream>\n#include <algorithm>\n#include <vector>\nusing namespace std;\nint main(){\n vector<int> v={5,2,9,1,7};\n sort(v.begin(),v.end());\n reverse(v.begin(),v.end());\n for(int i=0;i<v.size();i++){\n  cout<<v[i]<<" ";\n }\n cout<<endl;\n int minVal=*min_element(v.begin(),v.end());\n int maxVal=*max_element(v.begin(),v.end());\n cout<<minVal<<" "<<maxVal;\n return 0;\n}` },
      { name: "C++ Project 8", code: `include <fstream>\n#include <iostream>\nusing namespace std;\nint main(){\n ofstream file("test.txt");\n file<<"Hello World";\n file.close();\n ifstream in("test.txt");\n string line;\n while(getline(in,line)){\n  cout<<line;\n }\n in.close();\n return 0;\n}` },
      { name: "C++ Project 9", code: `#include <iostream>\n#include <string>\nusing namespace std;\nint main(){\n string s="madam";\n string rev="";\n for(int i=s.length()-1;i>=0;i--){\n  rev+=s[i];\n }\n cout<<rev<<endl;\n if(s==rev){\n  cout<<"Palindrome";\n }else{\n  cout<<"Not";\n }\n int count=0;\n for(char c:s){\n  if(c=='a'){\n   count++;\n  }\n }\n cout<<count;\n return 0;\n}` },
      { name: "C++ Project 10", code: `#include <string>\n#include <iostream>\nusing namespace std;\nint main(){\n string s="hello";\n string r="";\n for(int i=s.size()-1;i>=0;i--){\n  r+=s[i];\n }\n cout<<r<<endl;\n if(s==r){\n  cout<<"palindrome";\n }else{\n  cout<<"not";\n }\n return 0;\n}`}
    ];
  }

  // 👉 HTML
  if (lang === "HTML") {
    return [
      { name: "HTML Project 1", code: `<!DOCTYPE html>\n<html>\n<head>\n <title>Form</title>\n</head>\n<body>\n <h1>Registration</h1>\n <form>\n  <label>Name:</label>\n  <input type="text"><br>\n  <label>Email:</label>\n  <input type="email"><br>\n  <label>Password:</label>\n  <input type="password"><br>\n  <label>Gender:</label>\n  <input type="radio">Male\n  <input type="radio">Female<br>\n  <label>Country:</label>\n  <select>\n   <option>India</option>\n   <option>USA</option>\n  </select><br>\n  <button>Submit</button>\n </form>\n</body>\n</html>` },
      { name: "HTML Project 2", code: `<!DOCTYPE html>\n<html>\n<head>\n <title>Dashboard</title>\n</head>\n<body>\n <header>\n  <h1>My Dashboard</h1>\n </header>\n <nav>\n  <a href="#">Home</a>\n  <a href="#">Profile</a>\n  <a href="#">Settings</a>\n </nav>\n <section>\n  <h2>Overview</h2>\n  <p>Welcome user</p>\n </section>\n <section>\n  <h2>Stats</h2>\n  <ul>\n   <li>Users: 100</li>\n   <li>Sales: 200</li>\n  </ul>\n </section>\n <footer>\n  <p>Footer Info</p>\n </footer>\n</body>\n</html>` },
      { name: "HTML Project 3", code: `<input placeholder="Enter name">` },
      { name: "HTML Project 4", code: `<button>Click</button>` },
      { name: "HTML Project 5", code: `<ul><li>Item</li></ul>` },
      { name: "HTML Project 6", code: `<img src="">` },
      { name: "HTML Project 7", code: `<a href="#">Link</a>` },
      { name: "HTML Project 8", code: `<form></form>` },
      { name: "HTML Project 9", code: `<div>Box</div>` },
      { name: "HTML Project 10", code: `<footer>Footer</footer>` }
    ];
  }

  // 👉 CSS
  if (lang === "CSS") {
    return [
      { name: "CSS Project 1", code: `body{\nmargin:0;\npadding:0;\nfont-family:Arial;\nbackground:#f4f4f4;\n}\nh1{\ncolor:#333;\ntext-align:center;\npadding:20px;\n}\np{\nfont-size:18px;\ncolor:#666;\ntext-align:center;\n}` },
      { name: "CSS Project 2", code: `.container{\ndisplay:flex;\njustify-content:center;\nalign-items:center;\nheight:100vh;\n}\n.box{\nwidth:200px;\nheight:200px;\nbackground:blue;\ncolor:white;\ndisplay:flex;\nalign-items:center;\njustify-content:center;\n}` },
      { name: "CSS Project 3", code: `.nav{\ndisplay:flex;\nbackground:#222;\npadding:10px;\n}\n.nav a{\ncolor:white;\nmargin:0 10px;\ntext-decoration:none;\n}\n.nav a:hover{\ncolor:yellow;\n}` },
      { name: "CSS Project 4", code: `.card{\nwidth:250px;\npadding:20px;\nborder-radius:10px;\nbox-shadow:0 4px 8px rgba(0,0,0,0.2);\n}\n.card h3{\nmargin:0;\n}\n.card p{\ncolor:#555;\n}` },
      { name: "CSS Project 5", code: `.grid{\ndisplay:grid;\ngrid-template-columns:repeat(3,1fr);\ngap:10px;\n}\n.item{\nbackground:red;\npadding:20px;\ncolor:white;\ntext-align:center;\n}` },
      { name: "CSS Project 6", code: `button{\npadding:10px 20px;\nborder:none;\nbackground:green;\ncolor:white;\ncursor:pointer;\n}\nbutton:hover{\nbackground:darkgreen;\ntransform:scale(1.1);\n}` },
      { name: "CSS Project 7", code: `[5:59 pm, 15/05/2026] Garad: 8
[5:59 pm, 15/05/2026] Garad: .header{\nbackground:black;\ncolor:white;\npadding:15px;\ntext-align:center;\n}\n.footer{\nbackground:#333;\ncolor:white;\npadding:10px;\ntext-align:center;\n}` },
      { name: "CSS Project 8", code: `.form{\nwidth:300px;\nmargin:auto;\n}\ninput{\nwidth:100%;\npadding:10px;\nmargin:10px 0;\nborder:1px solid #ccc;\n}\ninput:focus{\nborder-color:blue;\noutline:none;\n}` },
      { name: "CSS Project 9", code: `img{\nwidth:100%;\nborder-radius:10px;\n}\n.gallery{\ndisplay:flex;\ngap:10px;\n}\n.gallery img:hover{\nopacity:0.7;\n}` },
      { name: "CSS Project 10", code: `.loader{\nborder:5px solid #f3f3f3;\nborder-top:5px solid blue;\nborder-radius:50%;\nwidth:40px;\nheight:40px;\nanimation:spin 1s linear infinite;\n}\n@keyframes spin{\n0%{transform:rotate(0deg);}\n100%{transform:rotate(360deg);}\n}` }
    ];
  }

  // 👉 JAVASCRIPT
  if (lang === "JavaScript") {
    return [
      { name: "JS Project 1", code: `let nums=[];\nfor(let i=0;i<15;i++){\nnums.push(Math.floor(Math.random()*100));\n}\nlet even=nums.filter(n=>n%2===0);\nlet sum=nums.reduce((a,b)=>a+b,0);\nlet avg=sum/nums.length;\nconsole.log("Nums:",nums);\nconsole.log("Even:",even);\nconsole.log("Sum:",sum);\nconsole.log("Avg:",avg);` },
      { name: "JS Project 2", code: `let text="javascript typing practice";\nlet words=text.split(" ");\nlet rev=words.map(w=>w.split("").reverse().join(""));\nlet upper=rev.map(w=>w.toUpperCase());\nlet count=upper.reduce((a,b)=>a+b.length,0);\nconsole.log(words);\nconsole.log(rev);\nconsole.log(upper);\nconsole.log(count);` },
      { name: "JS Project 3", code: `let obj={a:10,b:20,c:30};\nlet keys=Object.keys(obj);\nlet values=Object.values(obj);\nlet sum=values.reduce((a,b)=>a+b,0);\nlet avg=sum/values.length;\nkeys.forEach(k=>{\nconsole.log(k,obj[k]);\n});\nconsole.log("Sum:",sum);\nconsole.log("Avg:",avg);` },
      { name: "JS Project 4", code: `let arr=[1,2,3,4,5];\nlet sq=arr.map(n=>n*n);\nlet even=sq.filter(n=>n%2===0);\nlet total=even.reduce((a,b)=>a+b,0);\nfunction print(a){\na.forEach(x=>console.log(x));\n}\nprint(arr);\nprint(sq);\nprint(even);\nconsole.log(total);` },
      { name: "JS Project 5", code: `[6:10 pm, 15/05/2026] Garad: 5
[6:11 pm, 15/05/2026] Garad: let input=document.createElement("input");\ndocument.body.appendChild(input);\nlet btn=document.createElement("button");\nbtn.innerText="Click";\ndocument.body.appendChild(btn);\nbtn.addEventListener("click",()=>{\nalert(input.value);\n});` },
      { name: "JS Project 6", code: `let nums=[10,20,30,40];\nlet max=Math.max(...nums);\nlet min=Math.min(...nums);\nlet sorted=[...nums].sort((a,b)=>b-a);\nconsole.log(nums);\nconsole.log("Max:",max);\nconsole.log("Min:",min);\nconsole.log("Sorted:",sorted);` },
      { name: "JS Project 7", code: `let str="hello world";\nlet freq={};\nfor(let ch of str){\nfreq[ch]=(freq[ch]||0)+1;\n}\nfor(let k in freq){\nconsole.log(k,freq[k]);\n}` },
      { name: "JS Project 8", code: `[6:12 pm, 15/05/2026] Garad: 8
[6:13 pm, 15/05/2026] Garad: let list=[1,2,3,4,5];\nlet mul=1;\nfor(let x of list){\nmul*=x;\n}\nlet rev=[...list].reverse();\nconsole.log(list);\nconsole.log("Mul:",mul);\nconsole.log("Rev:",rev);` },
      { name: "JS Project 9", code: `let n=10;\nlet fib=[0,1];\nfor(let i=2;i<n;i++){\nfib.push(fib[i-1]+fib[i-2]);\n}\nlet sum=fib.reduce((a,b)=>a+b,0);\nconsole.log(fib);\nconsole.log(sum);` },
      { name: "JS Project 10", code: `[6:13 pm, 15/05/2026] Garad: 10
[6:13 pm, 15/05/2026] Garad: let colors=["red","green","blue"];\nlet idx=0;\nsetInterval(()=>{\ndocument.body.style.background=colors[idx];\nidx=(idx+1)%colors.length;\n},1000);` }
    ];
  }

  // 👉 TYPESCRIPT
  if (lang === "TypeScript") {
    return [
      { name: "TS Project 1", code: `let nums:number[]=[];\nfor(let i=0;i<15;i++){\nnums.push(Math.floor(Math.random()*100));\n}\nlet even:number[]=nums.filter(n=>n%2===0);\nlet sum:number=nums.reduce((a,b)=>a+b,0);\nlet avg:number=sum/nums.length;\nconsole.log(nums);\nconsole.log(even);\nconsole.log(sum);\nconsole.log(avg);` },
      { name: "TS Project 2", code: `let text:string="typescript typing practice";\nlet words:string[]=text.split(" ");\nlet rev:string[]=words.map(w=>w.split("").reverse().join(""));\nlet upper:string[]=rev.map(w=>w.toUpperCase());\nlet count:number=upper.reduce((a,b)=>a+b.length,0);\nconsole.log(words);\nconsole.log(rev);\nconsole.log(upper);\nconsole.log(count);` },
      { name: "TS Project 3", code: `interface User{\nname:string;\nage:number;\n}\nlet users:User[]=[{name:"A",age:20},{name:"B",age:25}];\nlet total:number=0;\nusers.forEach(u=>{\ntotal+=u.age;\n});\nlet avg:number=total/users.length;\nconsole.log(users);\nconsole.log(avg);` },
      { name: "TS Project 4", code: `let arr:number[]=[1,2,3,4,5];\nlet sq:number[]=arr.map(n=>n*n);\nlet even:number[]=sq.filter(n=>n%2===0);\nlet total:number=even.reduce((a,b)=>a+b,0);\nfunction print(a:number[]):void{\na.forEach(x=>console.log(x));\n}\nprint(arr);\nprint(sq);\nprint(even);\nconsole.log(total);` },
      { name: "TS Project 5", code: `let input=document.createElement("input");\ndocument.body.appendChild(input);\nlet btn=document.createElement("button");\nbtn.innerText="Submit";\ndocument.body.appendChild(btn);\nbtn.addEventListener("click",():void=>{\nalert(input.value);\n});` },
      { name: "TS Project 6", code: `let nums:number[]=[10,20,30,40];\nlet max:number=Math.max(...nums);\nlet min:number=Math.min(...nums);\nlet sorted:number[]=[...nums].sort((a,b)=>b-a);\nconsole.log(nums);\nconsole.log(max);\nconsole.log(min);\nconsole.log(sorted);` },
      { name: "TS Project 7", code: `let str:string="hello typescript";\nlet freq:Record<string,number>={};\nfor(let ch of str){\nfreq[ch]=(freq[ch]||0)+1;\n}\nfor(let k in freq){\nconsole.log(k,freq[k]);\n}` },
      { name: "TS Project 8", code: `[6:23 pm, 15/05/2026] Garad: 8
[6:23 pm, 15/05/2026] Garad: let list:number[]=[1,2,3,4,5];\nlet mul:number=1;\nfor(let x of list){\nmul*=x;\n}\nlet rev:number[]=[...list].reverse();\nconsole.log(list);\nconsole.log(mul);\nconsole.log(rev);` },
      { name: "TS Project 9", code: `[6:23 pm, 15/05/2026] Garad: 9
[6:23 pm, 15/05/2026] Garad: let n:number=10;\nlet fib:number[]=[0,1];\nfor(let i=2;i<n;i++){\nfib.push(fib[i-1]+fib[i-2]);\n}\nlet sum:number=fib.reduce((a,b)=>a+b,0);\nconsole.log(fib);\nconsole.log(sum);` },
      { name: "TS Project 10", code: `let colors:string[]=["red","green","blue"];\nlet idx:number=0;\nsetInterval(()=>{\ndocument.body.style.background=colors[idx];\nidx=(idx+1)%colors.length;\n},1000);` }
    ];
  }

  // 👉 KOTLIN
  if (lang === "Kotlin") {
    return [
      { name: "Kotlin Project 1", code: `fun main(){\nval nums=MutableList(15){(1..100).random()}\nval even=nums.filter{it%2==0}\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln(nums)\nprintln(even)\nprintln(sum)\nprintln(avg)\n}` },
      { name: "Kotlin Project 2", code: `fun main(){\nval nums=MutableList(15){(1..50).random()}\nval square=nums.map{it*it}\nval cube=nums.map{it*it*it}\nval even=nums.filter{it%2==0}\nval odd=nums.filter{it%2!=0}\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln("Numbers:")\nprintln(nums)\nprintln("Squares:")\nprintln(square)\nprintln("Cubes:")\nprintln(cube)\nprintln("Even:")\nprintln(even)\nprintln("Odd:")\nprintln(odd)\nprintln("Sum:")\nprintln(sum)\nprintln("Average:")\nprintln(avg)\n}`},
      { name: "Kotlin Project 3", code: `val text="kotlin typing practice"\nval words=text.split(" ")\nval rev=words.map{it.reversed()}\nval upper=rev.map{it.uppercase()}\nval count=upper.sumOf{it.length}\nprintln(words)\nprintln(rev)\nprintln(upper)\nprintln(count)` },
      { name: "Kotlin Project 4", code: `fun main(){\nval nums=MutableList(15){(1..100).random()}\nval even=nums.filter{it%2==0}\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln(nums)\nprintln(even)\nprintln(sum)\nprintln(avg)\n}` },
      { name: "Kotlin Project 5", code: `fun main(){\nval nums=MutableList(12){(1..50).random()}\nval square=nums.map{it*it}\nval cube=nums.map{it*it*it}\nval even=nums.filter{it%2==0}\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln("Numbers:")\nprintln(nums)\nprintln("Square:")\nprintln(square)\nprintln("Cube:")\nprintln(cube)\nprintln("Even:")\nprintln(even)\nprintln("Sum:")\nprintln(sum)\nprintln("Average:")\nprintln(avg)\n}` },
      { name: "Kotlin Project 6", code: `fun main(){\nval nums=MutableList(15){(1..40).random()}\nfun isPrime(n:Int):Boolean{\nif(n<2)return false\nfor(i in 2 until n){\nif(n%i==0)return false\n}\nreturn true\n}\nval primes=nums.filter{isPrime(it)}\nval count=primes.size\nval sum=nums.sum()\nprintln("Numbers:")\nprintln(nums)\nprintln("Primes:")\nprintln(primes)\nprintln("Count:")\nprintln(count)\nprintln("Sum:")\nprintln(sum)\n}` },
      { name: "Kotlin Project 7", code: `fun main(){\nval nums=MutableList(14){(1..60).random()}\nval greater=nums.filter{it>30}\nval smaller=nums.filter{it<=30}\nval sorted=nums.sorted()\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln("Numbers:")\nprintln(nums)\nprintln("Greater:")\nprintln(greater)\nprintln("Smaller:")\nprintln(smaller)\nprintln("Sorted:")\nprintln(sorted)\nprintln("Sum:")\nprintln(sum)\nprintln("Average:")\nprintln(avg)\n}` },
      { name: "Kotlin Project 8", code: `fun main(){\nval nums=MutableList(15){(1..80).random()}\nval mult2=nums.filter{it%2==0}\nval mult3=nums.filter{it%3==0}\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nval sorted=nums.sorted()\nprintln("Numbers:")\nprintln(nums)\nprintln("Multiple of 2:")\nprintln(mult2)\nprintln("Multiple of 3:")\nprintln(mult3)\nprintln("Sorted:")\nprintln(sorted)\nprintln("Sum:")\nprintln(sum)\nprintln("Average:")\nprintln(avg)\n}` },
      { name: "Kotlin Project 9", code: `fun main(){\nval nums=MutableList(12){(1..60).random()}\nval double=nums.map{it*2}\nval half=nums.map{it/2}\nval even=nums.filter{it%2==0}\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln("Numbers:")\nprintln(nums)\nprintln("Double:")\nprintln(double)\nprintln("Half:")\nprintln(half)\nprintln("Even:")\nprintln(even)\nprintln("Sum:")\nprintln(sum)\nprintln("Average:")\nprintln(avg)\n}` },
      { name: "Kotlin Project 10", code: `fun main(){\nval nums=MutableList(14){(1..70).random()}\nval greater=nums.filter{it>35}\nval smaller=nums.filter{it<=35}\nval unique=nums.toSet()\nval sum=nums.sum()\nval avg=sum.toDouble()/nums.size\nprintln("Numbers:")\nprintln(nums)\nprintln("Greater:")\nprintln(greater)\nprintln("Smaller:")\nprintln(smaller)\nprintln("Unique:")\nprintln(unique)\nprintln("Sum:")\nprintln(sum)\nprintln("Average:")\nprintln(avg)\n}` }
    ];
  }

  // 👉 SWIFT
  if (lang === "Swift") {
    return [
      { name: "Swift Project 1", code: `import Foundation\nlet nums=(0..<10).map{_ in Int.random(in:1...100)}\nlet even=nums.filter{$0%2==0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nprint(nums)\nprint(even)\nprint(sum)\nprint(avg)` },
      { name: "Swift Project 2", code: `import Foundation\nvar nums=(1...100).map{_ in Int.random(in:1...100)}\nlet even=nums.filter{$0%2==0}\nlet odd=nums.filter{$0%2!=0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nlet maxVal=nums.max()\nlet minVal=nums.min()\nprint("Numbers:")\nprint(nums)\nprint("Even:")\nprint(even)\nprint("Odd:")\nprint(odd)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)\nprint("Max:")\nprint(maxVal!)\nprint("Min:")\nprint(minVal!)` },
      { name: "Swift Project 3", code: `import Foundation\nvar nums=(1...50).map{_ in Int.random(in:1...50)}\nlet square=nums.map{$0*$0}\nlet cube=nums.map{$0*$0*$0}\nlet even=nums.filter{$0%2==0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nprint("Numbers:")\nprint(nums)\nprint("Square:")\nprint(square)\nprint("Cube:")\nprint(cube)\nprint("Even:")\nprint(even)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` },
      { name: "Swift Project 4", code: `import Foundation\nvar nums=(1...40).map{_ in Int.random(in:1...40)}\nfunc isPrime(_ n:Int)->Bool{\nif n<2{return false}\nfor i in 2..<n{\nif n%i==0{return false}\n}\nreturn true\n}\nlet primes=nums.filter{isPrime($0)}\nlet count=primes.count\nlet sum=nums.reduce(0,+)\nprint("Numbers:")\nprint(nums)\nprint("Primes:")\nprint(primes)\nprint("Count:")\nprint(count)\nprint("Sum:")\nprint(sum)` },
      { name: "Swift Project 5", code: `import Foundation\nvar nums=(1...30).map{_ in Int.random(in:1...30)}\nlet square=nums.map{$0*$0}\nlet cube=nums.map{$0*$0*$0}\nlet even=nums.filter{$0%2==0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nprint("Numbers:")\nprint(nums)\nprint("Square:")\nprint(square)\nprint("Cube:")\nprint(cube)\nprint("Even:")\nprint(even)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` },
      { name: "Swift Project 6", code: `import Foundation\nvar nums=(1...80).map{_ in Int.random(in:1...80)}\nlet mult2=nums.filter{$0%2==0}\nlet mult3=nums.filter{$0%3==0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nlet sorted=nums.sorted()\nprint("Numbers:")\nprint(nums)\nprint("Multiple of 2:")\nprint(mult2)\nprint("Multiple of 3:")\nprint(mult3)\nprint("Sorted:")\nprint(sorted)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` },
      { name: "Swift Project 7", code: `import Foundation\nvar nums=(1...60).map{_ in Int.random(in:1...60)}\nlet double=nums.map{$0*2}\nlet half=nums.map{$0/2}\nlet even=nums.filter{$0%2==0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nprint("Numbers:")\nprint(nums)\nprint("Double:")\nprint(double)\nprint("Half:")\nprint(half)\nprint("Even:")\nprint(even)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` },
      { name: "Swift Project 8", code: `import Foundation\nvar nums=(1...70).map{_ in Int.random(in:1...70)}\nlet greater=nums.filter{$0>35}\nlet smaller=nums.filter{$0<=35}\nlet unique=Set(nums)\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nprint("Numbers:")\nprint(nums)\nprint("Greater:")\nprint(greater)\nprint("Smaller:")\nprint(smaller)\nprint("Unique:")\nprint(unique)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` },
      { name: "Swift Project 9", code: `import Foundation\nvar nums1=(1...50).map{_ in Int.random(in:1...50)}\nvar nums2=(1...50).map{_ in Int.random(in:1...50)}\nlet combined=nums1+nums2\nlet common=Set(nums1).intersection(Set(nums2))\nlet unique=Set(combined)\nlet sum=combined.reduce(0,+)\nlet avg=Double(sum)/Double(combined.count)\nprint("List1:")\nprint(nums1)\nprint("List2:")\nprint(nums2)\nprint("Combined:")\nprint(combined)\nprint("Common:")\nprint(common)\nprint("Unique:")\nprint(unique)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` },
      { name: "Swift Project 10", code: `import Foundation\nvar nums=(1...50).map{_ in Int.random(in:1...50)}\nfunc fact(_ n:Int)->Int{\nvar f=1\nfor i in 1...n{\nf*=i\n}\nreturn f\n}\nlet factorials=nums.map{fact($0%10+1)}\nlet even=nums.filter{$0%2==0}\nlet sum=nums.reduce(0,+)\nlet avg=Double(sum)/Double(nums.count)\nprint("Numbers:")\nprint(nums)\nprint("Factorials:")\nprint(factorials)\nprint("Even:")\nprint(even)\nprint("Sum:")\nprint(sum)\nprint("Average:")\nprint(avg)` }
    ];
  }

  // 👉 NODE.JS
  if (lang === "Node.js") {
    return [
      { name: "Node Project 1", code: `const nums=Array.from({length:10},()=>Math.floor(Math.random()*100));\nconst even=nums.filter(n=>n%2===0);\nconst sum=nums.reduce((a,b)=>a+b,0);\nconst avg=sum/nums.length;\nconsole.log(nums);\nconsole.log(even);\nconsole.log(sum);\nconsole.log(avg);` },
      { name: "Node Project 2", code: `const nums=Array.from({length:15},()=>Math.floor(Math.random()*100)+1)\nconst even=nums.filter(n=>n%2===0)\nconst odd=nums.filter(n=>n%2!==0)\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconst max=Math.max(...nums)\nconst min=Math.min(...nums)\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Even Numbers:")\nconsole.log(even)\nconsole.log("Odd Numbers:")\nconsole.log(odd)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)\nconsole.log("Max:")\nconsole.log(max)\nconsole.log("Min:")\nconsole.log(min)` },
      { name: "Node Project 3", code: `[7:15 pm, 15/05/2026] Garad: 3
[7:15 pm, 15/05/2026] Garad: const nums=Array.from({length:12},()=>Math.floor(Math.random()*50)+1)\nconst square=nums.map(n=>n*n)\nconst cube=nums.map(n=>n*n*n)\nconst even=nums.filter(n=>n%2===0)\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Square:")\nconsole.log(square)\nconsole.log("Cube:")\nconsole.log(cube)\nconsole.log("Even Numbers:")\nconsole.log(even)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` },
      { name: "Node Project 4", code: `const nums=Array.from({length:15},()=>Math.floor(Math.random()*40)+1)\nfunction isPrime(n){\nif(n<2)return false\nfor(let i=2;i<n;i++){\nif(n%i===0)return false\n}\nreturn true\n}\nconst primes=nums.filter(n=>isPrime(n))\nconst count=primes.length\nconst sum=nums.reduce((a,b)=>a+b,0)\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Prime Numbers:")\nconsole.log(primes)\nconsole.log("Prime Count:")\nconsole.log(count)\nconsole.log("Sum:")\nconsole.log(sum)` },
      { name: "Node Project 5", code: `const nums=Array.from({length:14},()=>Math.floor(Math.random()*60)+1)\nconst greater=nums.filter(n=>n>30)\nconst smaller=nums.filter(n=>n<=30)\nconst sorted=[...nums].sort((a,b)=>a-b)\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Greater than 30:")\nconsole.log(greater)\nconsole.log("Less or equal 30:")\nconsole.log(smaller)\nconsole.log("Sorted:")\nconsole.log(sorted)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` },
      { name: "Node Project 6", code: `const nums=Array.from({length:15},()=>Math.floor(Math.random()*80)+1)\nconst mult2=nums.filter(n=>n%2===0)\nconst mult3=nums.filter(n=>n%3===0)\nconst both=nums.filter(n=>n%2===0 && n%3===0)\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Multiple of 2:")\nconsole.log(mult2)\nconsole.log("Multiple of 3:")\nconsole.log(mult3)\nconsole.log("Multiple of 2 & 3:")\nconsole.log(both)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` },
      { name: "Node Project 7", code: `const nums=Array.from({length:12},()=>Math.floor(Math.random()*60)+1)\nconst double=nums.map(n=>n*2)\nconst half=nums.map(n=>Math.floor(n/2))\nconst even=nums.filter(n=>n%2===0)\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Double Values:")\nconsole.log(double)\nconsole.log("Half Values:")\nconsole.log(half)\nconsole.log("Even Numbers:")\nconsole.log(even)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` },
      { name: "Node Project 8", code: `const nums=Array.from({length:14},()=>Math.floor(Math.random()*70)+1)\nconst greater=nums.filter(n=>n>35)\nconst smaller=nums.filter(n=>n<=35)\nconst unique=[...new Set(nums)]\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Greater than 35:")\nconsole.log(greater)\nconsole.log("Smaller or equal 35:")\nconsole.log(smaller)\nconsole.log("Unique Values:")\nconsole.log(unique)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` },
      { name: "Node Project 9", code: `const nums1=Array.from({length:10},()=>Math.floor(Math.random()*50)+1)\nconst nums2=Array.from({length:10},()=>Math.floor(Math.random()*50)+1)\nconst combined=[...nums1,...nums2]\nconst common=nums1.filter(n=>nums2.includes(n))\nconst unique=[...new Set(combined)]\nconst sum=combined.reduce((a,b)=>a+b,0)\nconst avg=sum/combined.length\nconsole.log("List 1:")\nconsole.log(nums1)\nconsole.log("List 2:")\nconsole.log(nums2)\nconsole.log("Combined List:")\nconsole.log(combined)\nconsole.log("Common Values:")\nconsole.log(common)\nconsole.log("Unique Values:")\nconsole.log(unique)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` },
      { name: "Node Project 10", code: `const nums=Array.from({length:12},()=>Math.floor(Math.random()10)+1)\nfunction fact(n){\nlet f=1\nfor(let i=1;i<=n;i++){\nf=i\n}\nreturn f\n}\nconst factorials=nums.map(n=>fact(n))\nconst even=nums.filter(n=>n%2===0)\nconst sum=nums.reduce((a,b)=>a+b,0)\nconst avg=sum/nums.length\nconsole.log("Numbers:")\nconsole.log(nums)\nconsole.log("Factorials:")\nconsole.log(factorials)\nconsole.log("Even Numbers:")\nconsole.log(even)\nconsole.log("Sum:")\nconsole.log(sum)\nconsole.log("Average:")\nconsole.log(avg)` }
    ];
  }

  // 👉 DART
  if (lang === "Dart") {
    return [
      { name: "Dart Project 1", code: `void main(){\nvar nums=List.generate(10,(_)=>Random().nextInt(100));\nvar even=nums.where((n)=>n%2==0).toList();\nvar sum=nums.reduce((a,b)=>a+b);\nvar avg=sum/nums.length;\nprint(nums);\nprint(even);\nprint(sum);\nprint(avg);\n}` },
      { name: "Dart Project 2", code: `void main(){\nString name="Krishna";\nint marks=82;\nprint("Student: $name");\nprint("Marks: $marks");\nif(marks>=90){\nprint("Grade A");\n}else if(marks>=75){\nprint("Grade B");\n}else if(marks>=50){\nprint("Grade C");\n}else{\nprint("Fail");\n}\nprint("Subjects:");\nList<String> sub=["Math","Sci","Eng","Hist"];\nfor(int i=0;i<sub.length;i++){\nprint(sub[i]);\n}\nprint("Counting:");\nfor(int j=1;j<=5;j++){\nprint("No: $j");\n}\nprint("End Program");` },
      { name: "Dart Project 3", code: `void main(){\nint a=20;\nint b=4;\nprint("Values: $a , $b");\nprint("Add: ${a+b}");\nprint("Sub: ${a-b}");\nprint("Mul: ${a*b}");\nif(b!=0){\nprint("Div: ${a/b}");\n}else{\nprint("Divide Error");\n}\nprint("Table of A");\nfor(int i=1;i<=10;i++){\nprint("$a x $i = ${a*i}");\n}\nprint("Reverse Loop");\nfor(int j=5;j>=1;j--){\nprint("Back: $j");\n}\nprint("Finish");` },
      { name: "Dart Project 4", code: `void main(){\nList<int> nums=[10,15,20,25];\nprint("Numbers:");\nnums.forEach((n){\nprint(n);\n});\nprint("Check Even/Odd");\nfor(int i=0;i<nums.length;i++){\nif(nums[i]%2==0){\nprint("${nums[i]} Even");\n}else{\nprint("${nums[i]} Odd");\n}\n}\nMap<String,int> data={"A":1,"B":2};\nprint("Map Data");\ndata.forEach((k,v){\nprint("$k=>$v");\n});\ndata["C"]=3;\nprint("Updated Map");\nprint(data);\nprint("End");` },
      { name: "Dart Project 5", code: `void main(){\nint num=5;\nint fact=1;\nprint("Number: $num");\nfor(int i=1;i<=num;i++){\nfact=fact*i;\nprint("Step $i => $fact");\n}\nprint("Factorial: $fact");\nprint("Extra Loop");\nfor(int j=1;j<=5;j++){\nprint("Count: $j");\n}\nprint("Done");` },
      { name: "Dart Project 6", code: `void main(){\nString text="dartlang";\nprint("Text: $text");\nfor(int i=0;i<text.length;i++){\nprint("Char: ${text[i]}");\n}\nprint("Check vowels");\nfor(int j=0;j<text.length;j++){\nif("aeiou".contains(text[j])){\nprint("${text[j]} vowel");\n}else{\nprint("${text[j]} consonant");\n}\n}\nprint("End");` },
      { name: "Dart Project 7", code: `void main(){\nList<int> marks=[70,80,90,60];\nint sum=0;\nprint("Marks List");\nfor(int i=0;i<marks.length;i++){\nsum+=marks[i];\nprint("Add ${marks[i]} => $sum");\n}\ndouble avg=sum/marks.length;\nprint("Total: $sum");\nprint("Average: $avg");\nif(avg>=75){\nprint("Good");\n}else{\nprint("Improve");\n}\nprint("Finish");` },
      { name: "Dart Project 8", code: `void main(){\nint num=7;\nbool prime=true;\nprint("Check: $num");\nfor(int i=2;i<num;i++){\nif(num%i==0){\nprime=false;\nbreak;\n}\n}\nif(prime){\nprint("Prime");\n}else{\nprint("Not Prime");\n}\nfor(int j=1;j<=5;j++){\nprint("Loop $j");\n}\nprint("End");` },
      { name: "Dart Project 9", code: `void main(){\nprint("Pattern");\nfor(int i=1;i<=5;i++){\nString row="";\nfor(int j=1;j<=i;j++){\nrow=row+"* ";\n}\nprint(row);\n}\nprint("Reverse");\nfor(int i=5;i>=1;i--){\nString row="";\nfor(int j=1;j<=i;j++){\nrow=row+"# ";\n}\nprint(row);\n}\nprint("Done");` },
      { name: "Dart Project 10", code: `void main(){\nint choice=2;\nprint("Menu");\nprint("1.Add");\nprint("2.Sub");\nprint("3.Exit");\nint a=10;\nint b=5;\nif(choice==1){\nprint("Add: ${a+b}");\n}else if(choice==2){\nprint("Sub: ${a-b}");\n}else{\nprint("Exit");\n}\nfor(int i=1;i<=3;i++){\nprint("Step $i");\n}\nprint("End");` }
    ];
  }

  // 👉 RUST
  if (lang === "Rust") {
    return [
      { name: "Rust Project 1", code: `[7:36 pm, 15/05/2026] Garad: 1
[7:36 pm, 15/05/2026] Garad: use rand::Rng;\nfn main(){\nlet mut rng=rand::thread_rng();\nlet nums:Vec<i32>=(0..10).map(|_|rng.gen_range(1..100)).collect();\nlet even:Vec<i32>=nums.iter().cloned().filter(|n|n%2==0).collect();\nlet sum:i32=nums.iter().sum();\nlet avg=sum as f64/nums.len() as f64;\nprintln!("{:?}",nums);\nprintln!("{:?}",even);\nprintln!("{}",sum);\nprintln!("{}",avg);\n}` },
      { name: "Rust Project 2", code: `fn main(){\nlet text="rust typing practice";\nlet words:Vec<&str>=text.split(" ").collect();\nlet rev:Vec<String>=words.iter().map(|w|w.chars().rev().collect()).collect();\nlet upper:Vec<String>=rev.iter().map(|w|w.to_uppercase()).collect();\nlet count:usize=upper.iter().map(|w|w.len()).sum();\nprintln!("{:?}",words);\nprintln!("{:?}",rev);\nprintln!("{:?}",upper);\nprintln!("{}",count);` },
      { name: "Rust Project 3", code: `use std::collections::HashMap;\nfn main(){\nlet mut map=HashMap::new();\nmap.insert("a",10);\nmap.insert("b",20);\nmap.insert("c",30);\nlet mut sum=0;\nfor v in map.values(){\nsum+=v;\n}\nlet avg=sum as f64/map.len() as f64;\nprintln!("{:?}",map);\nprintln!("{}",sum);\nprintln!("{}",avg);` },
      { name: "Rust Project 4", code: `use std::collections::HashMap;\nfn main(){\nlet mut students=HashMap::new();\nstudents.insert("Krishna",85);\nstudents.insert("Rahul",72);\nstudents.insert("Amit",91);\nprintln!("Student Data");\nfor (name,marks) in &students{\nprintln!("{} => {}",name,marks);\n}\nprintln!("Grade System");\nfor (name,marks) in &students{\nif *marks>=90{\nprintln!("{} Grade A",name);\n}else if *marks>=75{\nprintln!("{} Grade B",name);\n}else if *marks>=50{\nprintln!("{} Grade C",name);\n}else{\nprintln!("{} Fail",name);\n}\n}\nprintln!("Counting");\nfor i in 1..11{\nprintln!("No {}",i);\n}\nprintln!("End Program");` },
      { name: "Rust Project 5", code: `[7:40 pm, 15/05/2026] Garad: 5
[7:41 pm, 15/05/2026] Garad: fn main(){\nlet nums=vec![12,7,20,5,18,3];\nlet mut even=0;\nlet mut odd=0;\nprintln!("Numbers");\nfor n in &nums{\nprintln!("{}",n);\n}\nprintln!("Analyze");\nfor i in 0..nums.len(){\nif nums[i]%2==0{\neven+=1;\nprintln!("{} Even",nums[i]);\n}else{\nodd+=1;\nprintln!("{} Odd",nums[i]);\n}\n}\nprintln!("Even Count {}",even);\nprintln!("Odd Count {}",odd);\nlet mut sum=0;\nfor n in &nums{\nsum+=n;\nprintln!("Add {} => {}",n,sum);\n}\nprintln!("Total {}",sum);\nprintln!("Finish");` },
      { name: "Rust Project 6", code: `fn main(){\nlet mut balance=1000;\nprintln!("Bank System");\nprintln!("Start Balance {}",balance);\nlet deposit=500;\nbalance+=deposit;\nprintln!("Deposit {} => {}",deposit,balance);\nlet withdraw=300;\nif balance>=withdraw{\nbalance-=withdraw;\nprintln!("Withdraw {} => {}",withdraw,balance);\n}else{\nprintln!("Insufficient Balance");\n}\nprintln!("Transactions");\nfor i in 1..6{\nprintln!("Transaction {}",i);\n}\nprintln!("Check Status");\nif balance>1000{\nprintln!("Good Balance");\n}else{\nprintln!("Low Balance");\n}\nprintln!("Final Balance {}",balance);\nprintln!("End");` },
      { name: "Rust Project 7", code: `fn main(){\nprintln!("Tables Start");\nfor i in 1..6{\nprintln!("Table of {}",i);\nfor j in 1..11{\nlet result=i*j;\nprintln!("{} x {} = {}",i,j,result);\n}\nprintln!("------");\n}\nprintln!("Check Even/Odd");\nfor i in 1..21{\nif i%2==0{\nprintln!("{} Even",i);\n}else{\nprintln!("{} Odd",i);\n}\n}\nprintln!("Reverse Count");\nfor i in (1..11).rev(){\nprintln!("{}",i);\n}\nprintln!("End");` },
      { name: "Rust Project 8", code: `fn main(){\nlet text="rust programming language";\nprintln!("Text: {}",text);\nlet mut vowels=0;\nlet mut consonants=0;\nfor ch in text.chars(){\nif ch=='a'||ch=='e'||ch=='i'||ch=='o'||ch=='u'{\nvowels+=1;\nprintln!("{} vowel",ch);\n}else if ch!=' '{\nconsonants+=1;\nprintln!("{} consonant",ch);\n}\n}\nprintln!("Vowels {}",vowels);\nprintln!("Consonants {}",consonants);\nprintln!("Length {}",text.len());\nprintln!("Uppercase {}",text.to_uppercase());\nprintln!("Repeat");\nfor i in 1..6{\nprintln!("{} => {}",i,text);\n}\nprintln!("Done");` },
      { name: "Rust Project 9", code: `fn main(){\nlet mut arr=[45,12,78,3,56,9];\nprintln!("Original Array");\nfor i in 0..arr.len(){\nprintln!("{}",arr[i]);\n}\narr.sort();\nprintln!("Sorted Array");\nfor i in 0..arr.len(){\nprintln!("{}",arr[i]);\n}\nlet key=56;\nlet mut found=false;\nfor i in 0..arr.len(){\nif arr[i]==key{\nprintln!("Found {} at {}",key,i);\nfound=true;\n}\n}\nif !found{\nprintln!("Not Found");\n}\nprintln!("Sum");\nlet mut sum=0;\nfor i in 0..arr.len(){\nsum+=arr[i];\nprintln!("Add {} => {}",arr[i],sum);\n}\nprintln!("Total {}",sum);\nprintln!("End");` },
      { name: "Rust Project 10", code: `fn main(){\nprintln!("Pattern Start");\nfor i in 1..6{\nfor j in 1..=i{\nprint!("* ");\n}\nprintln!("");\n}\nprintln!("Number Pattern");\nfor i in 1..6{\nfor j in 1..=i{\nprint!("{} ",j);\n}\nprintln!("");\n}\nprintln!("Counter");\nlet mut count=0;\nfor i in 1..21{\ncount+=1;\nprintln!("Step {} => {}",i,count);\n}\nprintln!("Countdown");\nfor i in (1..11).rev(){\nprintln!("{}",i);\n}\nprintln!("Finish");` }
    ];
  }

  // 👉 C#
  if (lang === "C#") {
    return [
      { name: "C# Project 1", code: `using System;\nclass Program{\nstatic void Main(){\nstring[] names={"Krishna","Rahul","Amit"};\nint[] marks={85,72,91};\nConsole.WriteLine("Student Data");\nfor(int i=0;i<names.Length;i++){\nConsole.WriteLine(names[i]+" => "+marks[i]);\n}\nConsole.WriteLine("Grades");\nfor(int i=0;i<marks.Length;i++){\nif(marks[i]>=90){\nConsole.WriteLine(names[i]+" A");\n}else if(marks[i]>=75){\nConsole.WriteLine(names[i]+" B");\n}else{\nConsole.WriteLine(names[i]+" C");\n}\n}\nConsole.WriteLine("Count");\nfor(int i=1;i<=10;i++){\nConsole.WriteLine("No "+i);\n}\nConsole.WriteLine("End");\n}` },
      { name: "C# Project 2", code: `using System;\nclass Program{\nstatic void Main(){\nint[] nums={12,7,20,5,18,3};\nint even=0;\nint odd=0;\nConsole.WriteLine("Numbers");\nfor(int i=0;i<nums.Length;i++){\nConsole.WriteLine(nums[i]);\n}\nConsole.WriteLine("Check");\nfor(int i=0;i<nums.Length;i++){\nif(nums[i]%2==0){\neven++;\nConsole.WriteLine(nums[i]+" Even");\n}else{\nodd++;\nConsole.WriteLine(nums[i]+" Odd");\n}\n}\nConsole.WriteLine("Even "+even);\nConsole.WriteLine("Odd "+odd);\nConsole.WriteLine("Done");\n}` },
      { name: "C# Project 3", code: `using System;\nclass Program{\nstatic void Main(){\nint balance=1000;\nConsole.WriteLine("Start "+balance);\nint deposit=500;\nbalance+=deposit;\nConsole.WriteLine("Deposit "+deposit+" => "+balance);\nint withdraw=300;\nif(balance>=withdraw){\nbalance-=withdraw;\nConsole.WriteLine("Withdraw "+withdraw+" => "+balance);\n}else{\nConsole.WriteLine("Low Balance");\n}\nConsole.WriteLine("Transactions");\nfor(int i=1;i<=5;i++){\nConsole.WriteLine("Tx "+i);\n}\nif(balance>1000){\nConsole.WriteLine("Good");\n}else{\nConsole.WriteLine("Normal");\n}\nConsole.WriteLine("Final "+balance);\n}` },
      { name: "C# Project 4", code: `using System;\nclass Program{\nstatic void Main(){\nConsole.WriteLine("Pattern");\nfor(int i=1;i<=5;i++){\nfor(int j=1;j<=i;j++){\nConsole.Write("* ");\n}\nConsole.WriteLine();\n}\nint sum=0;\nConsole.WriteLine("Sum");\nfor(int i=1;i<=10;i++){\nsum+=i;\nConsole.WriteLine(i+" => "+sum);\n}\nConsole.WriteLine("Reverse");\nfor(int i=10;i>=1;i--){\nConsole.WriteLine(i);\n}\nConsole.WriteLine("End");\n}` },
      { name: "C# Project 5", code: `using System;\nclass Program{\nstatic void Main(){\nint[] nums={10,20,30,40,50};\nint sum=0;\nConsole.WriteLine("Numbers");\nfor(int i=0;i<nums.Length;i++){\nConsole.WriteLine(nums[i]);\n}\nConsole.WriteLine("Adding");\nfor(int i=0;i<nums.Length;i++){\nsum+=nums[i];\nConsole.WriteLine(nums[i]+" => "+sum);\n}\ndouble avg=sum/nums.Length;\nConsole.WriteLine("Total "+sum);\nConsole.WriteLine("Average "+avg);\nConsole.WriteLine("Check");\nfor(int i=0;i<nums.Length;i++){\nif(nums[i]>avg){\nConsole.WriteLine(nums[i]+" Above Avg");\n}else{\nConsole.WriteLine(nums[i]+" Below Avg");\n}\n}\n}` },
      { name: "C# Project 6", code: `using System;\nclass Program{\nstatic void Main(){\nint n=5;\nint fact=1;\nConsole.WriteLine("Number "+n);\nfor(int i=1;i<=n;i++){\nfact*=i;\nConsole.WriteLine("Step "+i+" => "+fact);\n}\nConsole.WriteLine("Factorial "+fact);\nConsole.WriteLine("Extra Loop");\nfor(int i=1;i<=10;i++){\nConsole.WriteLine("No "+i);\n}\nConsole.WriteLine("Reverse");\nfor(int i=10;i>=1;i--){\nConsole.WriteLine(i);\n}\nConsole.WriteLine("Done");\n}` },
      { name: "C# Project 7", code: `using System;\nclass Program{\nstatic void Main(){\nint n=17;\nbool isPrime=true;\nConsole.WriteLine("Check "+n);\nfor(int i=2;i<n;i++){\nif(n%i==0){\nisPrime=false;\nConsole.WriteLine("Divisible by "+i);\n}\n}\nif(isPrime){\nConsole.WriteLine("Prime");\n}else{\nConsole.WriteLine("Not Prime");\n}\nConsole.WriteLine("Numbers");\nfor(int i=1;i<=20;i++){\nConsole.WriteLine(i);\n}\nConsole.WriteLine("End");\n}` },
      { name: "C# Project 8", code: `using System;\nclass Program{\nstatic void Main(){\nstring text="hello world";\nstring rev="";\nConsole.WriteLine("Text "+text);\nfor(int i=text.Length-1;i>=0;i--){\nrev+=text[i];\nConsole.WriteLine("Step "+rev);\n}\nConsole.WriteLine("Reverse "+rev);\nConsole.WriteLine("Length "+text.Length);\nConsole.WriteLine("Upper "+text.ToUpper());\nConsole.WriteLine("Loop");\nfor(int i=1;i<=5;i++){\nConsole.WriteLine(i+" => "+text);\n}\nConsole.WriteLine("Done");\n}` },
      { name: "C# Project 9", code: `using System;\nclass Program{\nstatic void Main(){\nint n=5;\nConsole.WriteLine("Table "+n);\nfor(int i=1;i<=10;i++){\nint res=n*i;\nConsole.WriteLine(n+" x "+i+" = "+res);\n}\nConsole.WriteLine("Extra Tables");\nfor(int i=1;i<=3;i++){\nfor(int j=1;j<=5;j++){\nConsole.WriteLine(i+" x "+j+" = "+(i*j));\n}\n}\nConsole.WriteLine("End");\n}` },
      { name: "C# Project 10", code: `using System;\nclass Program{\nstatic void Main(){\nstring user="admin";\nstring pass="1234";\nstring inputUser="admin";\nstring inputPass="1234";\nConsole.WriteLine("Login");\nif(inputUser==user && inputPass==pass){\nConsole.WriteLine("Success");\n}else{\nConsole.WriteLine("Fail");\n}\nConsole.WriteLine("Attempts");\nfor(int i=1;i<=3;i++){\nConsole.WriteLine("Try "+i);\n}\nConsole.WriteLine("Status");\nif(inputUser==user){\nConsole.WriteLine("User OK");\n}else{\nConsole.WriteLine("Wrong User");\n}\nConsole.WriteLine("End");\n}` }
    ];
  }

  // 👉 R
  if (lang === "R") {
    return [
      { name: "R Project 1", code: `nums<-c(10,20,30,40,50)\nprint("Numbers")\nfor(i in nums){\nprint(i)\n}\nsum<-0\nprint("Adding")\nfor(i in nums){\nsum<-sum+i\nprint(paste(i,"=>",sum))\n}\navg<-sum/length(nums)\nprint(paste("Total",sum))\nprint(paste("Average",avg))\nprint("Check")\nfor(i in nums){\nif(i>avg){\nprint(paste(i,"Above Avg"))\n}else{\nprint(paste(i,"Below Avg"))\n}\n}\nprint("End")` },
      { name: "R Project 2", code: `nums<-c(12,7,20,5,18,3)\neven<-0\nodd<-0\nprint("Numbers")\nfor(i in nums){\nprint(i)\n}\nprint("Check")\nfor(i in nums){\nif(i%%2==0){\neven<-even+1\nprint(paste(i,"Even"))\n}else{\nodd<-odd+1\nprint(paste(i,"Odd"))\n}\n}\nprint(paste("Even",even))\nprint(paste("Odd",odd))\nprint("Loop")\nfor(i in 1:10){\nprint(i)\n}\nprint("Done")` },
      { name: "R Project 3", code: `n<-5\nfact<-1\nprint(paste("Number",n))\nfor(i in 1:n){\nfact<-fact*i\nprint(paste("Step",i,"=>",fact))\n}\nprint(paste("Factorial",fact))\nprint("Extra Loop")\nfor(i in 1:10){\nprint(i)\n}\nprint("Reverse")\nfor(i in 10:1){\nprint(i)\n}\nprint("End")` },
      { name: "R Project 4", code: `n<-17\nisPrime<-TRUE\nprint(paste("Check",n))\nfor(i in 2:(n-1)){\nif(n%%i==0){\nisPrime<-FALSE\nprint(paste("Divisible",i))\n}\n}\nif(isPrime){\nprint("Prime")\n}else{\nprint("Not Prime")\n}\nprint("Numbers")\nfor(i in 1:20){\nprint(i)\n}\nprint("End")` },
      { name: "R Project 5", code: `text<-"hello"\nrev<-""\nprint(paste("Text",text))\nfor(i in nchar(text):1){\nrev<-paste0(rev,substr(text,i,i))\nprint(paste("Step",rev))\n}\nprint(paste("Reverse",rev))\nprint(paste("Length",nchar(text)))\nprint("Loop")\nfor(i in 1:5){\nprint(paste(i,text))\n}\nprint("Done")` },
      { name: "R Project 6", code: `n<-5\nprint(paste("Table",n))\nfor(i in 1:10){\nres<-n*i\nprint(paste(n,"x",i,"=",res))\n}\nprint("Extra Tables")\nfor(i in 1:3){\nfor(j in 1:5){\nprint(paste(i,"x",j,"=",i*j))\n}\n}\nprint("Check Even")\nfor(i in 1:10){\nif(i%%2==0){\nprint(paste(i,"Even"))\n}\n}\nprint("End")` },
      { name: "R Project 7", code: `nums<-c(45,12,78,3,56,9)\nmaxv<-nums[1]\nminv<-nums[1]\nprint("Numbers")\nfor(i in nums){\nprint(i)\nif(i>maxv){\nmaxv<-i\n}\nif(i<minv){\nminv<-i\n}\n}\nprint(paste("Max",maxv))\nprint(paste("Min",minv))\nprint("Loop")\nfor(i in 1:5){\nprint(i)\n}\nprint("Done")` },
      { name: "R Project 8", code: `text<-"programming"\nvowels<-0\ncons<-0\nprint(paste("Text",text))\nfor(i in 1:nchar(text)){\nch<-substr(text,i,i)\nif(ch%in%c("a","e","i","o","u")){\nvowels<-vowels+1\nprint(paste(ch,"vowel"))\n}else{\ncons<-cons+1\nprint(paste(ch,"cons"))\n}\n}\nprint(paste("Vowels",vowels))\nprint(paste("Cons",cons))\nprint("End")` },
      { name: "R Project 9", code: `n<-10\nsum<-0\nprint(paste("Number",n))\nfor(i in 1:n){\nsum<-sum+i\nprint(paste(i,"=>",sum))\n}\nprint(paste("Total",sum))\nprint("Reverse")\nfor(i in n:1){\nprint(i)\n}\nprint("Check Even")\nfor(i in 1:n){\nif(i%%2==0){\nprint(paste(i,"Even"))\n}\n}\nprint("Done")` },
      { name: "R Project 10", code: `user<-"admin"\npass<-"1234"\ninputUser<-"admin"\ninputPass<-"1234"\nprint("Login")\nif(inputUser==user && inputPass==pass){\nprint("Success")\n}else{\nprint("Fail")\n}\nprint("Attempts")\nfor(i in 1:3){\nprint(paste("Try",i))\n}\nprint("Check User")\nif(inputUser==user){\nprint("User OK")\n}else{\nprint("Wrong User")\n}\nprint("End")` }
    ];
  }

  // 👉 DEFAULT
  return [
    { name: lang+" Project 1", code: `// code` },
    { name: lang+" Project 2", code: `// code` },
    { name: lang+" Project 3", code: `// code` },
    { name: lang+" Project 4", code: `// code` },
    { name: lang+" Project 5", code: `// code` },
    { name: lang+" Project 6", code: `// code` },
    { name: lang+" Project 7", code: `// code` },
    { name: lang+" Project 8", code: `// code` },
    { name: lang+" Project 9", code: `// code` },
    { name: lang+" Project 10", code: `// code` }
  ];
}